### PR TITLE
Add FFI bindings

### PR DESCRIPTION
**Pull request by jpnurmi**
Generated with help of [ffigen](https://github.com/dart-lang/ffigen) (from dart-lang/ffigen#126).

### CODE REVIEW

**Comment by jpnurmi** [comment]
NOTE: Nested structs require Dart SDK https://github.com/dart-lang/sdk/commit/b6b82dd3ac756b39e7fe9cab21f060fae74e358d or later. As of right now, the Dart SDK (2.12.0-179.0.dev) pinned to the latest Flutter master is still too old.

**Comment by escamoteur** [comment]
Awesome, that was quick work!!!

**Comment by escamoteur** [comment]
Oh, where did you get the Dawn Header from?

**Comment by jpnurmi** [comment]
> Oh, where did you get the Dawn Header from?

At first, I was using https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h but I switched to the one from the latest [Dawn main](https://dawn.googlesource.com/dawn/) (commit sha1 86980018b3f2786aeb5ded1220ec94bc927fa6b2) because we need to setup the Dawn proc table in order to be able to call any "wgpuXxx" methods from dawn_proc.so and the symbols should match with the header.

**Comment by escamoteur** [comment]
Interesting because in the Dawn documetation I read it like that the webgpu.h isn't in source control but get's created dynamically by the build system from the JSON file.

**Comment by jpnurmi** [comment]
Yeah, presumably it will be necessary to bundle prebuilt `libdawn_native` and `libdawn_proc` so/dll/dylib (too complicated to build on the fly), so it's good to have the generated header and bindings from the exact same Dawn version.

**Pull request merged**
